import type { Metadata } from "next";
import LegalDocument, { type LegalSection } from "@/app/components/LegalDocument";

export const metadata: Metadata = { title: "Privacy Policy | Bidlane", description: "How Bidlane collects, uses, shares, and protects personal information." };

const sections: LegalSection[] = [
  { id: "scope", title: "Scope of this policy", content: <p>This Privacy Policy explains how Bidlane handles personal information when you visit our website, create an account, submit or watch a listing, bid, comment, upload content, or contact us. It does not govern third-party websites or services that have their own privacy policies.</p> },
  { id: "collect", title: "Information we collect", content: <><h3>Information you provide</h3><p>This may include your name, email address, password, profile image, messages to us, comments, bids, watchlist choices, and vehicle listing details such as photos, description, mileage, and location.</p><h3>Information collected automatically</h3><p>When you use Bidlane, we may receive device and browser information, IP address, approximate location, pages viewed, interactions, referring pages, timestamps, cookie identifiers, and diagnostic logs.</p><h3>Information from other sources</h3><p>If you sign in through an identity provider, we receive the account information that provider makes available according to your settings. We may also receive information from service providers that help us prevent fraud, host content, and operate the platform.</p></> },
  { id: "use", title: "How we use information", content: <><p>We use personal information to:</p><ul><li>Provide accounts, listings, auctions, bidding, comments, watchlists, and support.</li><li>Authenticate users and protect the marketplace from fraud, abuse, and security threats.</li><li>Send service messages, auction updates, and other communications you request.</li><li>Understand performance, troubleshoot problems, and improve our features.</li><li>Enforce our terms, resolve disputes, and comply with legal obligations.</li></ul></> },
  { id: "share", title: "How we share information", content: <><p>We do not sell your personal information for money. We may share information:</p><ul><li><strong>Publicly and with other users:</strong> profile details, listings, comments, bid activity, and other content intended for the marketplace may be visible to others.</li><li><strong>With service providers:</strong> companies supporting hosting, databases, authentication, image storage, real-time updates, analytics, security, and communications may process information for us.</li><li><strong>For legal and safety reasons:</strong> when reasonably necessary to comply with law, respond to valid process, enforce our terms, or protect people, rights, and the service.</li><li><strong>In a business transaction:</strong> as part of a financing, merger, acquisition, reorganization, or sale of assets, subject to appropriate safeguards.</li></ul><p>We may share aggregated or de-identified information that cannot reasonably identify you.</p></> },
  { id: "cookies", title: "Cookies and similar technology", content: <p>We use cookies and similar technologies to keep you signed in, remember preferences, maintain security, understand service usage, and operate core features. Browser settings can block or delete cookies, but some parts of Bidlane may stop working correctly. Where required, we will request consent before using non-essential cookies.</p> },
  { id: "choices", title: "Your choices and rights", content: <><p>You can update certain profile information and communication choices through your account or by contacting us. Depending on where you live, you may have rights to access, correct, delete, or receive a copy of your personal information; object to or restrict certain processing; or withdraw consent.</p><p>To make a request, email <a href="mailto:support@bidlane.com">support@bidlane.com</a>. We may need to verify your identity. Some information may be retained when required by law or needed for security, fraud prevention, transaction records, or legal claims. You may appeal a denied request by replying to our decision.</p></> },
  { id: "retention", title: "Retention and security", content: <><p>We retain personal information only as long as reasonably necessary for the purposes described here, including providing the service, keeping auction and transaction records, meeting legal obligations, resolving disputes, and preventing abuse. Retention periods vary by the type and sensitivity of information.</p><p>We use reasonable administrative, technical, and organizational safeguards. No online system is completely secure, so we cannot guarantee absolute security. Use a strong, unique password and contact us if you believe your account has been compromised.</p></> },
  { id: "international", title: "International data transfers", content: <p>Bidlane and its service providers may process information in countries other than where you live. Those countries may have different data protection laws. Where required, we use recognized safeguards for these transfers and take steps designed to protect information consistently with this policy.</p> },
  { id: "children", title: "Children&apos;s privacy", content: <p>Bidlane is not directed to children under 18, and we do not knowingly collect personal information from them. If you believe a child has provided us personal information, contact us so we can investigate and delete it where appropriate.</p> },
  { id: "updates", title: "Updates and contact", content: <><p>We may update this policy as our service or legal obligations change. We will revise the effective date and provide additional notice when a change is material.</p><p>For privacy questions or requests, email <a href="mailto:support@bidlane.com">support@bidlane.com</a> or use our <a href="/contact">contact page</a>.</p></> },
];

export default function PrivacyPage() {
  return <LegalDocument eyebrow="Your data, clearly explained" title="Privacy Policy" description="What we collect, why we use it, and the choices you have when you use Bidlane." effectiveDate="September 7, 2026" sections={sections} companion={{ label: "Terms of Service", href: "/terms" }} />;
}
