import type { Metadata } from "next";
import LegalDocument, { type LegalSection } from "@/app/components/LegalDocument";

export const metadata: Metadata = { title: "Terms of Service | Bidlane", description: "The terms that govern access to and use of the Bidlane vehicle auction marketplace." };

const sections: LegalSection[] = [
  { id: "agreement", title: "Agreement to these terms", content: <p>These Terms of Service form a binding agreement between you and Bidlane. By creating an account, browsing listings, submitting a vehicle, commenting, or placing a bid, you agree to these terms and our <a href="/privacy">Privacy Policy</a>. If you do not agree, do not use the service.</p> },
  { id: "eligibility", title: "Eligibility and accounts", content: <><p>You must be at least 18 years old and legally able to enter a contract to use transactional features. You agree to provide accurate information and keep it current.</p><ul><li>You are responsible for your login credentials and activity under your account.</li><li>Do not impersonate another person, create accounts to evade restrictions, or share access in a way that compromises the service.</li><li>Tell us promptly at <a href="mailto:support@bidlane.com">support@bidlane.com</a> if you suspect unauthorized access.</li></ul></> },
  { id: "marketplace", title: "Our role as a marketplace", content: <><p>Bidlane provides technology for vehicle owners and prospective buyers to meet, communicate, and participate in auctions. Unless a listing expressly says otherwise, Bidlane does not own, inspect, possess, or sell the listed vehicle and is not a party to the final sale.</p><p>We may review, format, approve, reject, pause, or remove listings and activity to operate and protect the marketplace, but we do not guarantee a vehicle&apos;s condition, history, identity, legality, availability, or the accuracy of user-provided information.</p></> },
  { id: "listings", title: "Seller responsibilities", content: <><p>If you submit a vehicle, you represent that you have the legal authority to offer it and that your listing is complete and not misleading. You must disclose known material defects, title or lien issues, accident history, modifications, and other facts a reasonable buyer would consider important.</p><ul><li>Use recent, accurate photos and content you have the right to share.</li><li>Keep the vehicle available during the auction and do not manipulate bidding.</li><li>Cooperate reasonably with questions, inspection requests, and the winning bidder.</li><li>If the reserve is met, complete the transaction on the terms presented in the listing, subject to applicable law.</li></ul></> },
  { id: "bidding", title: "Bids and auction results", content: <><p><strong>A bid is a serious commitment.</strong> By bidding, you confirm that you have reviewed the listing, can complete the purchase, and authorize Bidlane to record and display the bid. You may not retract or manipulate a bid except where required by law or expressly approved by Bidlane.</p><p>The displayed timer controls the auction. A bid placed near closing may extend the auction. When an auction ends, the highest bidder may be expected to purchase the vehicle if the reserve has been met. Buyers and sellers are responsible for final documentation, payment, taxes, registration, shipping, insurance, and compliance with applicable law.</p><p>Bidlane may invalidate suspicious, erroneous, or technically compromised activity. We do not guarantee that a bid, notification, countdown, or auction result will be uninterrupted or error-free.</p></> },
  { id: "conduct", title: "Acceptable use", content: <><p>Use Bidlane lawfully and respectfully. You may not:</p><ul><li>Post false, deceptive, infringing, threatening, discriminatory, or unlawful content.</li><li>Shill bid, coordinate bids, interfere with an auction, or artificially influence price or engagement.</li><li>Scrape, reverse engineer, overload, probe, or bypass security or access controls.</li><li>Introduce malware, collect other users&apos; personal information improperly, or use the service for spam.</li></ul><p>We may remove content or suspend or terminate access when we reasonably believe these terms, another person&apos;s rights, or the safety and integrity of the marketplace are at risk.</p></> },
  { id: "content", title: "Content and intellectual property", content: <><p>You keep ownership of content you submit. You grant Bidlane a worldwide, non-exclusive, royalty-free license to host, store, reproduce, format, display, and distribute that content as needed to operate, promote, and improve the service. This license ends when the content is deleted, except for copies reasonably retained in backups, legal records, or prior promotional materials.</p><p>Bidlane&apos;s name, branding, interface, software, and original content are protected by intellectual property laws. These terms do not grant you ownership of them.</p></> },
  { id: "disclaimers", title: "Disclaimers and liability", content: <><p>To the fullest extent permitted by law, Bidlane is provided “as is” and “as available,” without warranties of merchantability, fitness for a particular purpose, title, or non-infringement. Vehicle transactions carry inherent risks, and you are responsible for your own inspection, due diligence, and decisions.</p><p>To the fullest extent permitted by law, Bidlane and its personnel will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, lost profits or data, vehicle condition, or disputes between users. Nothing here excludes liability that cannot legally be excluded.</p></> },
  { id: "changes", title: "Changes and termination", content: <><p>We may change or discontinue features and may update these terms. If a change is material, we will provide reasonable notice through the service or by email when appropriate. Continued use after the effective date means you accept the updated terms.</p><p>You may stop using Bidlane at any time. Provisions that by their nature should survive—such as ownership, licenses already granted, disclaimers, liability limits, and dispute-related terms—will remain in effect.</p></> },
  { id: "contact", title: "Questions and legal notices", content: <p>Questions or notices about these terms can be sent to <a href="mailto:support@bidlane.com">support@bidlane.com</a> or through our <a href="/contact">contact page</a>. These terms are governed by the laws that apply where Bidlane operates, without overriding consumer protections that apply where you live.</p> },
];

export default function TermsPage() {
  return <LegalDocument eyebrow="The rules of the road" title="Terms of Service" description="The straightforward rules that help keep Bidlane useful, fair, and safe for buyers, sellers, and enthusiasts." effectiveDate="September 7, 2026" sections={sections} companion={{ label: "Privacy Policy", href: "/privacy" }} />;
}
